---
version: '3.2'

services:
  mysql:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: dataflow
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
    expose:
      - 3306
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
  redis:
    image: redis:2.8
    expose:
      - "6379"
    volumes:
      - type: volume
        source: redis_data
        target: /data
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - type: volume
        source: rabbitmq_data
        target: /var/lib/rabbitmq
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - type: volume
        source: zookeeper_data
        target: /var/lib/zookeeper/data
      - type: volume
        source: zookeeper_log
        target: /var/lib/zookeeper/log
      - type: volume
        source: zookeeper_secrets
        target: /etc/zookeeper/secrets
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - type: volume
        source: kafka_secrets
        target: /etc/kafka/secrets
      - type: volume
        source: kafka_data
        target: /var/lib/kafka/data
  dataflow-server:
    image: springcloud/spring-cloud-dataflow-server-local:${DATAFLOW_VERSION}
    container_name: dataflow-server
    ports:
      - "9393:9393"
    environment:
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers=kafka:29092
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.zkNodes=zookeeper:32181
      - spring_datasource_url=jdbc:mysql://mysql:3306/dataflow
      - spring_datasource_username=root
      - spring_datasource_password=rootpw
      - spring_datasource_driver-class-name=org.mariadb.jdbc.Driver
      - spring.cloud.dataflow.applicationProperties.stream.spring.rabbitmq.host=rabbitmq
      - spring.cloud.dataflow.applicationProperties.stream.spring.redis.host=redis
      - spring_redis_host=redis
    depends_on:
      - kafka
      - mysql
      - rabbitmq
      - redis
    volumes:
      - type: volume
        source: dataflow_data
        target: /tmp
  app-import:
    image: alpine:3.7
    depends_on:
      - dataflow-server
    command: >
      /bin/sh -c "
        while ! nc -z dataflow-server 9393;
        do
          sleep 1;
        done;
        wget -qO- 'http://dataflow-server:9393/apps'  --post-data='uri=http://bit.ly/Darwin-GA-stream-applications-rabbit-maven&force=true';
        echo 'Stream apps imported'
        "
volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
  zookeeper_data:
  zookeeper_log:
  zookeeper_secrets:
  kafka_secrets:
  kafka_data:
  dataflow_data:
 